# Generated by Django 4.1.5 on 2023-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_PostCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_PostCategory',
            new_name='post_category',
        ),
    ]
